using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Sentinel.Catalog;

/// <summary>Seeds the catalog/contracts from data/catalog/*.json (generated by
/// data/scripts/generate_catalog.py). Idempotent: skips if products already exist.</summary>
public static class Seeder
{
    private static readonly JsonSerializerOptions J = new()
    {
        // seed JSON is snake_case (gpo_name, list_price, applicable_rooms); map it to
        // the PascalCase seed records. Without this, GpoName/ListPrice deserialize null/0.
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
    };

    public static async Task SeedAsync(CatalogDb db, string seedDir, ILogger log)
    {
        await db.Database.EnsureCreatedAsync();
        if (await db.Products.AnyAsync())
        {
            log.LogInformation("Catalog already seeded ({Count} products).", await db.Products.CountAsync());
            return;
        }

        var catalogPath = Path.Combine(seedDir, "catalog.json");
        var contractsPath = Path.Combine(seedDir, "contracts.json");
        if (!File.Exists(catalogPath))
        {
            log.LogWarning("Seed file not found at {Path}; starting empty. Run generate_catalog.py.", catalogPath);
            return;
        }

        var rnd = new Random(20260626);
        var rawProducts = JsonSerializer.Deserialize<List<SeedProduct>>(
            await File.ReadAllTextAsync(catalogPath), J) ?? new();

        foreach (var sp in rawProducts)
        {
            db.Products.Add(new Product
            {
                Sku = sp.Sku,
                Name = sp.Name,
                Category = sp.Category,
                Subcategory = sp.Subcategory,
                Vendor = sp.Vendor,
                Unit = sp.Unit,
                ListPrice = sp.ListPrice,
                Compliant = sp.Compliant,
                StockOnHand = rnd.Next(0, 250),
                ApplicableRooms = sp.ApplicableRooms ?? new(),
                Attributes = sp.Attributes ?? new(),
            });
        }

        if (File.Exists(contractsPath))
        {
            var c = JsonSerializer.Deserialize<SeedContracts>(
                await File.ReadAllTextAsync(contractsPath), J);
            foreach (var ct in c?.Contracts ?? new())
                db.Contracts.Add(new Contract { Id = ct.Id, GpoName = ct.GpoName, Discount = ct.Discount });
            await db.SaveChangesAsync(); // contracts + products first (FK targets)

            foreach (var cp in c?.ContractPrices ?? new())
                db.ContractPrices.Add(new ContractPrice { Sku = cp.Sku, ContractId = cp.ContractId, Price = cp.Price });
        }
        else
        {
            await db.SaveChangesAsync();
        }

        await db.SaveChangesAsync();
        log.LogInformation("Seeded {P} products, {C} contract prices.",
            await db.Products.CountAsync(), await db.ContractPrices.CountAsync());
    }

    // ---- seed-file shapes ----
    private record SeedProduct(
        string Sku, string Name, string Category, string Subcategory, string Vendor,
        string Unit, decimal ListPrice, bool Compliant,
        List<string>? ApplicableRooms, Dictionary<string, JsonElement>? Attributes);

    private record SeedContracts(List<SeedContract> Contracts, List<SeedPrice> ContractPrices);
    private record SeedContract(string Id, string GpoName, decimal Discount);
    private record SeedPrice(string Sku, string ContractId, decimal Price);
}
